name: writer-cps-full
version: 0.0.0.1
synopsis: WriteT and RWST monad transformers (Reexport with all dependencies)
description:
  The WriterT and RWST monad transformers provided by writer-cps-transformers
  are written in continuation passing style and avoid the space-leak
  problem of the traditional Control.Monad.Trans.Writer.Strict and Control.Monad.Trans.Writer.Lazy.
  This package reexports from writer-cps-transformers and provides all missing
  orphan instances, e.g. from mtl.
category: Control
author: Daniel Mendler
maintainer: mail@daniel-mendler.de
copyright: 2017 Daniel Mendler
license: BSD3
github: minad/writer-cps-full

dependencies:
- base >= 4.5 && < 5
- writer-cps-transformers >= 0.1.1.2 && < 0.2
- writer-cps-mtl >= 0.1.1.2 && < 0.2
- writer-cps-lens >= 0.1.0.0 && < 0.2
- writer-cps-morph >= 0.1.0.1 && < 0.2

tested-with:
  GHC == 7.4.2,
  GHC == 7.6.3,
  GHC == 7.8.4,
  GHC == 7.10.3,
  GHC == 8.0.1

library:
  source-dirs: src
